### ISSUE TITLE
Affected by Windows version?

### ISSUE THREAD

**Issue by asherber** [ricksladkey/SmoothScroll#14]
I'm using the v2.0.2 of this extension with VS2019 16.2 on an HP laptop. In addition to running VS locally, I also frequently remote from the laptop into a Citrix VDI desktop and run the same version of VS there.

In the VDI, SmoothScroll works exactly as designed, and if I disable the extension there, I can see the old blocky scroll motion. But in local VS, the extension does not work. (I know that it used to work on the same laptop, in VS2017 and before the last Windows update.)

Obviously, it's the same trackpad being used to drive local VS and VS on my VDI. It's also the same version of the extension and the same version of VS. But my VDI is running Win10 v1709, and my laptop is running Win10 v1903.

Is it possible that the Windows version has some effect here? Is there something else on my laptop that would have made the extension stop working?

**Comment by ricksladkey** [comment]
@asherber To be honest, I still don't any system running any version of Windows 10, so I cannot help you there. However, you can do some diagnostics to see if your mouse wheel driver is working as it needs to in order for the smooth scrolling to work by following the instructions in issue #3.

**Comment by asherber** [comment]
It is something wonky with the driver. When I follow the steps you suggested, I see that all the deltas are 120 or -120, just as in the other ticket. 

I uninstalled my Synaptics driver in order to rollback to the previous version, and before I rebooted I actually did get smooth scrolling in VS (I guess using some default MS driver). After I installed the older driver, I lost smooth scrolling again.

Frustrating.

**Comment by ricksladkey** [comment]
@asherber Different drivers are different and some actually change their behavior depending on the application. You can verify whether this is the case by finding some other application where smooth scrolling works, for example, chrome. Then you can verify that the mouse driver is capable of generating fine-grained mouse wheel events for at least one other application besides Visual Studio.

If that works, ideally there would be some UI to configure application exceptions. Ha ha, or as a last resort, even poke around in the registry.
