### ISSUE TITLE
Support for Visual Studio 14

### ISSUE THREAD

**Issue by matteocontrini** [ricksladkey/SmoothScroll#2]
Hi,
I'm using Visual Studio 2015 Preview and the extension is not yet compatible.
Can the manifest be updated with the new 14.0 version support? I have no experience with extensions so I don't know exactly how the syntax works :)

Thank you

**Comment by ricksladkey** [comment]
I'll try the preview too and test it out.

**Comment by ricksladkey** [comment]
Made those changes, published it to the Visual Studio Gallery, and tested it locally in Visual Studio 2015 CTP 5.  Please give it a try and if it works for you, feel free to close this issue.  Thanks.

**Comment by matteocontrini** [comment]
It works fine. Thanks!
