### ISSUE TITLE
Visual Studio 15 support

### ISSUE THREAD

**Issue by xperiandri** [ricksladkey/SmoothScroll#9]

**Comment by VladimirPobedinskiy** [comment]
Yes. It not work in VS 2015.

**Comment by apkd** [comment]
I *desperately* needed this extension so I [forked it and updated the project for VS2017](https://github.com/apkd/SmoothScroll) (a relatively simple operation). If the author prefers, I can take the repository down when the original extension is updated.

**Comment by ricksladkey** [comment]
I've update the extension to VSIX v3, bumped the version number, and published it to the Visual Studio Gallery. Sorry for the delay but I had a heck of a time installing Visual Studio 2017 to be able to test it out. My first attempt to install 2017 borked my computer so badly I had to restore from backup, which was not that recent. For a time after that I was gun shy, but now have finally pulled the trigger.

**Comment by xperiandri** [comment]
Cool! Thanks
